### ISSUE TITLE
Code postal des communes est incorrect

### ISSUE THREAD

**Issue by Khaledsb** [kossa/algerian-cities#10]
Code postal des communes est incorrect

**Comment by kossa** [comment]
Send a PR 😊

**Comment by n4ss1m** [comment]
Yes there's a mistake, The postal code is linked to the post office, not the communes ( has many post offices ), 

so I think we need to drop `code postal` because the data isn't correct.

**Comment by kossa** [comment]
@n4ss1m I think each commune has only one postal code

**Comment by n4ss1m** [comment]
@kossa Yes, that's right

**Comment by kossa** [comment]
So it's correct :)

**Comment by n4ss1m** [comment]
@kossa, could you enable Discussions for this repo to facilitate community interaction? Thanks!

**Comment by kossa** [comment]
Done.
