### ISSUE TITLE
[QUESTION] : How to remove api endpoints

### ISSUE THREAD

**Issue by alberto-mortadella** [kossa/algerian-cities#16]
hey, im using swagger so when installing algerian-cities package, i have those new apis popping in my swagger interface
![image](https://github.com/user-attachments/assets/356c62a0-2577-4024-bd3b-1e4c86ffd657)

how can i remove / edit them

thank u

**Comment by kossa** [comment]
Which tool you use to generate swagger doc? (I think swagger will not automatically generate all endpoints)

**Comment by alberto-mortadella** [comment]
im using [g4t/swagger](https://github.com/hussein4alaa/laravel-g4t-swagger-auto-generate)

**Comment by kossa** [comment]
I created an issue for you https://github.com/hussein4alaa/laravel-g4t-swagger-auto-generate/issues/82 :)

**Comment by n4ss1m** [comment]
you can disable it by following steps here :
https://github.com/kossa/algerian-cities?tab=readme-ov-file#api-availability-toggle

**Comment by kossa** [comment]
Please make sure to get the last version :)
